version: '3.8'
services:
  web:
    volumes:
      - ./app:/code
      - /code/node_modules
      - ./data.nosync:/code/static/data
    ports:
      - "127.0.0.1:3000:3000"
    command: >-
      sh -c "yarn install && yarn dev"
