// Generates types/metadata.ts from the /metadata JSON Schema copied from skope-api.
// Run with `npm run types:metadata` after updating contracts/metadata-1.0.0.schema.json.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

// Where the copy in contracts/ came from. Update it with the copy.
const SCHEMA_SOURCE =
  "skope-api timeseries/app/registry/schemas/metadata-1.0.0.schema.json at 88f9383";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = resolve(HERE, "../contracts/metadata-1.0.0.schema.json");
const TYPES_PATH = resolve(HERE, "../types/metadata.ts");

// json-schema-to-typescript doesn't read 2020-12 `prefixItems`, so tuples
// become draft-07 `items` arrays. Property titles are dropped so fields get
// inline types instead of one alias each; $defs keep theirs and name the
// interfaces.
function prepare(node, isDefinition = false) {
  if (Array.isArray(node)) return node.map((item) => prepare(item));
  if (node === null || typeof node !== "object") return node;
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === "title" && !isDefinition) continue;
    if (key === "prefixItems") {
      out.items = prepare(value);
    } else if (key === "$defs" || key === "properties") {
      // Keys here are names, not keywords: a property may be called "title".
      out[key] = Object.fromEntries(
        Object.entries(value).map(([name, schema]) => [
          name,
          prepare(schema, key === "$defs"),
        ]),
      );
    } else {
      out[key] = prepare(value);
    }
  }
  return out;
}

export async function generateMetadataTypes() {
  const schema = JSON.parse(await readFile(SCHEMA_PATH, "utf8"));
  const prepared = { ...prepare(schema), title: "MetadataResponse" };
  return compile(prepared, "MetadataResponse", {
    additionalProperties: false,
    bannerComment: [
      "/**",
      " * Generated by scripts/metadata-types.mjs from contracts/metadata-1.0.0.schema.json,",
      ` * a copy of ${SCHEMA_SOURCE}.`,
      " * Do not edit by hand: update the schema copy and run `npm run types:metadata`.",
      " */",
    ].join("\n"),
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeFile(TYPES_PATH, await generateMetadataTypes());
  console.log(`Wrote ${TYPES_PATH}`);
}
