/**
 * Generated by scripts/metadata-types.mjs from contracts/metadata-1.0.0.schema.json,
 * a copy of skope-api timeseries/app/registry/schemas/metadata-1.0.0.schema.json at 88f9383.
 * Do not edit by hand: update the schema copy and run `npm run types:metadata`.
 */

export interface MetadataResponse {
  datasets: Dataset[];
  schema_version?: "1.0.0";
}
export interface Dataset {
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: [number, number, number, number];
  citation: string | null;
  declaration_digest: string;
  default_variable: string | null;
  description: string;
  doi: string | null;
  id: string;
  license: string;
  lineage: string | null;
  links: OverviewLink[];
  map_view: MapView | null;
  order: number;
  profile: string;
  providers: OverviewProvider[];
  publications: OverviewPublication[];
  region_name: string;
  release_id: string;
  resolution_label: string;
  time: Time;
  title: string;
  uncertainty: OverviewUncertainty | null;
  variables: Variable[];
  version: string;
}
export interface OverviewLink {
  href: string;
  rel: string;
  title?: string | null;
}
export interface MapView {
  center: MapCenter;
  zoom: number;
}
export interface MapCenter {
  lat: number;
  lon: number;
}
export interface OverviewProvider {
  name: string;
  roles: ("producer" | "licensor" | "processor" | "host")[];
  url?: string | null;
}
export interface OverviewPublication {
  citation: string;
  doi?: string | null;
}
export interface Time {
  count: number;
  end: string;
  kind: "regular" | "enumerated";
  origin: string;
  precision: string;
  step: string | null;
  values: string[] | null;
}
export interface OverviewUncertainty {
  methodology_href: string | null;
  summary: string;
}
export interface Variable {
  categories: {
    [k: string]: string;
  } | null;
  category: string | null;
  description: string;
  display: Display;
  id: string;
  labels: {
    [k: string]: string;
  } | null;
  order: number;
  title: string;
  unit: string;
}
export interface Display {
  colors: string[];
  note: string | null;
  palette: string;
  range: [number, number] | null;
  ticks: number | number[];
  type: "continuous" | "categorical";
}
